### ISSUE TITLE
Feature request: Show landmine thrower's range

### ISSUE THREAD

**Issue by diamond-lizard** [calcwizard/landmine-thrower#1]
When I hover my mouse over a turret or hold a turret in my hand, Factorio shows me its range via a green circle surrounding the turret, which makes deciding on where to place the turret much easier.

It would be great if landmine thrower's range could be shown this way as well.

It would also be useful to see the landmine's thrower's range when holding a landmine or when about to paste a bunch of landmines with copy/cut/paste or from a blueprint.

**Comment by calcwizard** [comment]
Artillery turrets don't have that functionality built in. The closest is the generic `radius_visualisation_specification`, however the range on that is fixed so it won't increase as the range of the turret is increased.  I've opened a request to have range visualization available for artillery turrets.
