### ISSUE TITLE
Landmine thrower keeps throwing mines which have been cut or placed by robots

### ISSUE THREAD

**Issue by diamond-lizard** [calcwizard/landmine-thrower#2]
When I cut some landmines via CONTROL-C and my robots pick them up, the landmine thrower lays them down again.  Needless to say, this makes moving mine fields impractical.

The landmine thrower also seems to try to place down mines over ones that I've already had placed by my robots with copy/paste.

It would be great if the landmine thrower only replaced mines which were destroyed, not ones which I've cut or which have not been destroyed but have already been placed by my robots.

**Comment by diamond-lizard** [comment]
It looks like the behavior of the land mine throwers continuing to throw landmines after cutting/deleting them happens when this cutting/deleting is done soon after laying them down.  After some time has passed they can be cut/deleted without the throwers trying to lay them down again.

By the way, I'm on Factorio 0.18.22, and Land Mine Thrower 18.0.0

**Comment by calcwizard** [comment]
Thanks, I've fixed the issues with removing flares after the ghost is no longer present. I'm just waiting to hear back from the request I opened for #1 before releasing it, but the bugfixes have already been merged.
